version: 0.1
phases:
  install:
    runtime-versions:
      python:3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deplyment_package.zip .
      - cd ..
      - zip -g deplyment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name test-AC-CTP-github-to-lambda-py --zip-file fileb://deplyment_package.zip
      - echo "Done!"